### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by InTheProcess** [InTheProcess/unicode-graphics-engine#2]
- [x] Add logging system for debugging purposes
- [ ] Add the ability to draw circles
- [ ] Add the ability to draw polygons
- [ ] Sync update speed to delta time
- [ ] Add speed control
- [ ] Organize project hierarchy
- [ ] Add a quit function
- [x] Make a way to configure the engine to your needs
- [ ] Add settings for each canvas
- [ ] Fix Critical Bugs
- [ ] Add shape outline variants
